// Shows Attack Surface Reduction rule hits for the last 30 days
DeviceEvents
| where TimeGenerated > ago(30d)
| where ActionType startswith "Asr"
| extend AdditionalFieldsStr = tostring(AdditionalFields)
| extend IsAudit = extractjson("$.IsAudit", AdditionalFieldsStr)
| extend RuleId = extractjson("$.RuleId", AdditionalFieldsStr)
| project TimeGenerated, DeviceName, ActionType, FileName, FolderPath, SHA256, InitiatingProcessFileName, InitiatingProcessCommandLine, AccountName, AccountDomain, IsAudit, RuleId