// Shows where user was allowed to change their password because Entra Password Protection is is set to "Audit" and not to "Enforced"
AuditLogs
| where ResultDescription has "PasswordDoesnotComplyFuzzyPolicy"
| where OperationName in (
    "Change user password",
    "Change password (self-service)",
    "Reset user password",
    "Reset password (self-service)"
)
| mv-expand TargetResource = TargetResources
| extend UserPrincipalName = tostring(TargetResource.userPrincipalName)
| extend UserName = tostring(TargetResource.displayName)
| project TimeGenerated, OperationName, ResultDescription, UserPrincipalName, UserName, TargetResource